wcコマンド完成
Miya096jp/ruby-practices pull request #9
Opened 2024-07-21 05:52 UTC by Miya096jp

2024-07-24 09:45 UTC, u1tnk requested changes
何点かコメントしましたが、全般的に見直して欲しいです。

- メソッド分割し過ぎ
    - メソッドに分割することは基本的には良いこととされていますが、一行レベルの処理で分かれ過ぎていて、今データがどうなっているかの理解しづらくなっています。
         - 何回も呼ばれるような処理なら一行レベルでもメソッド化することはあります。
- 全体の処理の流れが分かりづらい
    - データ取得→計算→出力という流れになってると思いますが、途中計算しつつ出力用のpaddingした状態で受け渡ししたりしていて、明確になっていない
        - どんなオプションでも出力できるように情報量の足りたデータ構造を作って、それをオプションと一緒に出力処理に渡すようにすると良いかと思います。
    - 出力用に整形する処理は一箇所で大丈夫と思います。

2024-07-24 09:45 UTC, u1tnk commented on 05.wc/wc.rb
> +def process_files(file_names, **params)
`**`は受け渡しともに不要です。

付けて渡すと… 例えば以下のようにするとそのままparamsの中身が分解されて count_linesに入るという機能です。逆に受け側で付けると複数で渡されたものをhashにしてくれるので、現状だと何もつけないのと同じで意味が無いです。

```
def process_files(file_names, count_lines:, ...)
```

2024-07-24 09:45 UTC, u1tnk commented on 05.wc/wc.rb
> +def append_names(padded_statistics, file_names)
このレベルなら分割せずに他の処理で一緒にできそうです。

2024-07-24 09:45 UTC, u1tnk commented on 05.wc/wc.rb
> +def default_set(file_text)
こちらもメソッドにする必要を感じません。
また、名前も意図が分からないです。

2024-07-24 09:45 UTC, u1tnk commented on 05.wc/wc.rb
> +    array = []
こういうデータを計算するメソッドは配列ではない方が良いです。
順番が1番が count_linesである、しかもオプションによって変化するだと使う方は難しいです。
hashで 名前付けて管理したいですね。

2024-07-24 09:45 UTC, u1tnk commented on 05.wc/wc.rb
> +    array = default_set(file_text) if array.empty?
- array.empty?だと意図が分からないので、ちゃんとoptionが全てfalseのときというのを条件にしたい
    - と書いたのですが、そもそも計算自体は常にするようにした方がシンプルですね。オプションを見て出力だけしないようにすれば良いので。

2024-07-24 09:45 UTC, u1tnk commented on 05.wc/wc.rb
> +    array << file_text.count("\n") if count_lines == true
`== true` は不要ですね。
JavaScriptやPHPなどでは明確にする必要があったりもしますが、rubyだと nil/false 以外は真なので通常変数だけで大丈夫です。

2024-07-26 00:11 UTC, Miya096jp commented on 05.wc/wc.rb
> +def default_set(file_text)
最初はまとめていたのですが、rubocopに処理が複雑だから分けるように言われて分けました。ハッシュや配列や条件分岐がごちゃごちゃに混じっていたからだと思います。この変数名は読む人はわからないですね。全般的に変数名やメソッド名はかなり考えたので、もはや頭が回っていなかったんだと思います💧　render_statistics_with_no_optionsなどにすれば適当かなと思いますが、再提出用に試行錯誤してみて、分ける必要はまったくなかったと理解しました！

2024-07-26 00:18 UTC, Miya096jp commented on 05.wc/wc.rb
> +    array = []
これまで配列ばかり使って、ハッシュはほとんど使ってきませんでした。難しく感じていたので避けていた部分もあるのですが、再提出のコードでハッシュを使ってみて、少しずつ使い方がわかってきました！

2024-07-26 00:22 UTC, Miya096jp commented on 05.wc/wc.rb
> +def append_names(padded_statistics, file_names)
分けるべきかまとめるべきか、適宜考えるようにします。メソッドの定義に慣れてきたので、あまり深く考えずに細かく分けようとしていました。

2024-07-26 00:31 UTC, Miya096jp commented on 05.wc/wc.rb
> +def process_files(file_names, **params)
ここはlsコマンドのお手本コードを真似してみたのですが、動いたからよしとして深く理解していませんでした。ご説明ありがとうございます。初めて使う記号や演算子はしっかり確認して使うようにします。

2024-07-26 00:36 UTC, Miya096jp commented on 05.wc/wc.rb
> +    array = default_set(file_text) if array.empty?
オプションを見て出力だけしない処理ですが、丸１日考え続けてやっと書けました。あっていることを祈ります🙏

2024-07-26 00:38 UTC, Miya096jp commented on 05.wc/wc.rb
> +    array << file_text.count("\n") if count_lines == true
ご指摘ありがとうございます。javascriptでは必要なんですね。混同しないように気をつけます！

2024-07-27 15:38 UTC, u1tnk requested changes
前回よりメソッドの分け方が良くなったのでだいぶ読みやすかったです！ 👍
とはいえもうちょっと指摘があるので確認お願いします 🙏

2024-07-27 15:38 UTC, u1tnk commented on 05.wc/wc.rb
> +text_counts = get_text_counts(file_texts)
メインの流れをメソッドの外に置くものアリなんですが、こういう風にメソッドの合間に置くと全体の流れが見えづらくなるので一箇所にまとめましょう。

2024-07-27 15:38 UTC, u1tnk commented on 05.wc/wc.rb
> +def get_text_counts(file_texts)
ファイル名の一覧をもらって、ファイル名のカウント一覧を作る…
とすると、ファイル名とその結果が「配列の同じ位置」というちょっと危ういまとまりになっちゃいますね。
一見して分からないです。

ファイル名を一緒に入れるなり hashにするなりして一つのデータ構造に同じまとまりだと明確に分かるようにしたいです。

2024-07-27 15:38 UTC, u1tnk commented on 05.wc/wc.rb
> +def get_total(text_counts)
これはtext_countsの配列の最後にtotalをつっこんでると思うんですが、以下のような問題があります。

- メソッドの引数に追加する形は良くない
    - totalを計算してreturnして、呼び出し元で保存する方が良い。
    - 入力と出力を明確にした方が分かりやすいから
- text_countsというファイルの件数一覧の一つの配列の中に並列で結果が入るという分かりづらさ。

2024-07-27 15:38 UTC, u1tnk commented on 05.wc/wc.rb
> +  keys = text_counts.first.keys
このkeysは別のメソッドの中身の変数に依存してるので分かりづらいですね。重複はしちゃいますが、定数にしてしまって良いと思います。
で、せっかく keys配列を作ったのなら一行分の出力のときにも使えそうです。

2024-07-27 15:38 UTC, u1tnk commented on 05.wc/wc.rb
> +  max_length = keys.map do |key|
totalもmax_lengthもデータ全部確認する必要があるんで同じ場所でやるとスッキリしそうですね。

2024-07-27 15:38 UTC, u1tnk commented on 05.wc/wc.rb
> +    unless !count_lines && !count_words && !count_bytes
unlessは認知的にifよりもほんのちょっと分かりづらいので、複雑な条件のときはunlessは使わずにifにするというのが一般的です。
複雑のラインをどこにするかはある程度個人差がありますが、私は && や || があるともうifにするようにしています。

2024-07-27 15:38 UTC, u1tnk commented on 05.wc/wc.rb
> +puts render(text_counts, **params)
これは https://blog.jnito.com/entry/2022/11/28/072945 この 伊藤さんのブログで指摘されている問題と思うので、一読して改善してみてください 💪

2024-07-28 00:57 UTC, Miya096jp commented on 05.wc/wc.rb
> +def get_text_counts(file_texts)
これまでの習慣でこういうやり方をよく使っていたので、これからはデータ構造を考えながら実装するようにします。この段階でhashにまとめてみました。

2024-07-28 01:50 UTC, Miya096jp commented on 05.wc/wc.rb
> +def get_total(text_counts)
なるほど、勉強になります！

2024-07-28 06:08 UTC, Miya096jp commented on 05.wc/wc.rb
> +    unless !count_lines && !count_words && !count_bytes
ここは最初はif !count_lines &&...としていたのですが、ロジックが複雑だということでrubocopに引っかかったため、unlessに変えてパスしました。でも人間にとってはifの方が読みやすいですよね。元に戻してみたのですが、やはりrubocopに引っかかります。ifでも複雑に思えないのですが、これでいいでしょうか？

2024-07-28 07:47 UTC, Miya096jp commented on 05.wc/wc.rb
> +  keys = text_counts.first.keys
確かに、定数にしてしまえばよかったです。毎回定数にできるところを指摘されますが、なかなか自分で気がつきません😇　出力についてはかなり長時間考えましたが書き直せました。おかげで少しずつハッシュの挙動のイメージができてきたように思います！

2024-07-28 07:50 UTC, Miya096jp commented on 05.wc/wc.rb
> +  max_length = keys.map do |key|
機能で分割するのではなく、共通の引数でまとめる考え方もあるんですね。確かに、どちらも必要な値を求めるという意味でも共通しているし、一括りにしてもわかりやすいですね。

2024-07-28 07:54 UTC, Miya096jp commented on 05.wc/wc.rb
> +puts render(text_counts, **params)
読みやすく書いたつもりがマトリョーショカになってたんですね😅　ブログを何度も読んで考え方を身につけたいと思います。書き直したバージョンは改善されていればいいのですが。ご確認よろしくお願いいたします！

2024-07-28 13:52 UTC, u1tnk commented on 05.wc/wc.rb
> +  max_length = keys.map do |key|
同じタイミングというだけで同じメソッドじゃなくても良いですけどね。(もちろん同じでも良い)

2024-07-28 13:53 UTC, u1tnk commented on 05.wc/wc.rb
> +    unless !count_lines && !count_words && !count_bytes
rubocopはメソッドの複雑さですよね？ オプションの結果取るときに計算しちゃっておくのが良いかと思います。

2024-07-28 14:57 UTC, u1tnk requested changes

2024-07-28 14:57 UTC, u1tnk commented on 05.wc/wc.rb
> +def get_total_and_max_lengths(text_counts, file_names)
text_countsにfile_nameが入ったのでfile_namesは不要だと思います。

2024-07-28 14:57 UTC, u1tnk commented on 05.wc/wc.rb
> +def get_total_and_max_lengths(text_counts, file_names)
ここは僕が同じときにやった方が良いって言っていて申し訳無いんですが、このメソッドはちょっと複雑なので分けた方が良さそうですね。

text_counts生成以降renderの前にやって頂けば大丈夫です。

2024-07-28 14:57 UTC, u1tnk commented on 05.wc/wc.rb
> +text_counts << total if file_names.size >= 2
totalを text_countsに入れるのは 意味の違うレコードが同じ配列に入っているので良くないです。
別の変数で保持すれば良いと思います。

2024-07-28 14:57 UTC, u1tnk commented on 05.wc/wc.rb
> +params = { count_lines: false, count_words: false, count_bytes: false }
いまさらですみませんが、 paramsは 引数全般で使うので汎用的過ぎてちょっと分かりづらい(サンプルコードでよく見るやつなんです)のと、OptionParser使っているしoptionsの方が良いかなと。

2024-07-29 01:46 UTC, Miya096jp commented on 05.wc/wc.rb
> +    unless !count_lines && !count_words && !count_bytes
そうです、そんなに複雑に思えないのですが。自分なりに考えてやってみました。認識が合っているといいのですが。とりあえず複雑さのエラーは出なくなりました！

2024-07-29 01:50 UTC, Miya096jp commented on 05.wc/wc.rb
> +def get_total_and_max_lengths(text_counts, file_names)
これは不注意でした、気をつけます。

もっとシンプルなロジックを思いつけばよかったのですが。再度分割しました！

2024-07-29 02:01 UTC, Miya096jp commented on 05.wc/wc.rb
> +text_counts << total if file_names.size >= 2
なるほど、データベース的に考えると、データソースと計算結果は別レコードの扱いということですね。出力用にrender_text_countsメソッドとrender_total_countsメソッドを作り、ソースレコードとトータルレコードを別々に出力してみました。

2024-07-29 02:02 UTC, Miya096jp commented on 05.wc/wc.rb
> +params = { count_lines: false, count_words: false, count_bytes: false }
optionsに変更しました！

2024-07-29 15:43 UTC, u1tnk requested changes

2024-07-29 15:43 UTC, u1tnk commented on 05.wc/wc.rb
> +if file_names.size >= 2
ここはもっと共通化できますね。
確かに不必要な処理はしないというのは効率的なのですが、読みやすさとのトレードオフなので、速度が遅いものでなければとりあえず計算はしちゃって、出力だけしないようにすればもっとシンプルになります。

2024-07-29 15:43 UTC, u1tnk commented on 05.wc/wc.rb
> +  text_counts = format_text_counts(text_counts, max_lengths, keys_to_keep)
マトリョーシカ状態は良くないのですが、formatとrender は機能的には同じものでformatが一行分、renderが複数行という関係なので、renderからformatを呼ぶようにしてここでは呼ばない方が良いと思います。
更に言うと formatとrenderは近い意味(慣用的にはformatは整形するだけ、renderは整形と出力にも使います) で、今回は複数行と一行という違いなので同じ名前＋説明が良いかと思います。 formatとrenderだとどっちが一行だっけ？ってなるので。

2024-07-29 15:43 UTC, u1tnk commented on 05.wc/wc.rb
> +def render_total_counts(total_counts)
render_text_countsとrender_total_counts は同じですね。
変数は分ける必要はありますが、同じ処理なので一つのメソッドにしましょう。

2024-07-29 15:43 UTC, u1tnk commented on 05.wc/wc.rb
> +keys_to_keep = []
この名前は必要な keysを保持しておくって意味なんだと思いますが、to_keepは微妙ですね。
変数は大体保持しておくものなので。
全部のkeysじゃなくてオプションで設定されたkeyってことを表す名前にしましょう。(to_keepもそのニュアンスだったんだとは思いますが)
あと keys_xxx もたまに使いますが、 xxx_keys の方がよく使います。

2024-07-29 15:43 UTC, u1tnk commented on 05.wc/wc.rb
> +  keys_to_keep << :name
nameは絶対必要なものだから keysに入れなくても良い気はしますが…
ここに入れた方が全体処理はシンプルになってるので入れても良いです。
ただ、入れるにしても絶対に通る処理は if/else両方に入れるんじゃなくて if/elseの外に置いて絶対通ることを一目で分かるようにしたいです。

2024-07-29 21:44 UTC, Miya096jp commented on 05.wc/wc.rb
> +if file_names.size >= 2
なるほど、そこは柔軟に考えていいんですね。

2024-07-29 22:04 UTC, Miya096jp commented on 05.wc/wc.rb
> +  text_counts = format_text_counts(text_counts, max_lengths, keys_to_keep)
なるほど、こういうパターンだと入れ子にした方がわかりやすいですね。
変数名は、コードと合わせて読めば意味がわかるぐらいの具体性でつけてみました。ちなみにここは、renderメソッドに出力の機能があるからformatは整形、renderは出力で明確に区別できると誤解していました。出力はputsメソッドで行っていてrenderは整形だけで出力機能はないですね。

2024-07-29 22:04 UTC, Miya096jp commented on 05.wc/wc.rb
> +def render_total_counts(total_counts)
了解です。1つにまとめました！

2024-07-29 22:33 UTC, Miya096jp commented on 05.wc/wc.rb
> +keys_to_keep = []
確かに、この変数名はかなり曖昧ですね。option_keysとしてみました。
ふだん後修飾をよく使うので習慣的に変数にも使っていましたが、前修飾で1つの名詞にした方がスッキリしますね。おかげさまで、だんだん感覚的に理解できるようになってきたと思います。

2024-07-29 23:25 UTC, Miya096jp commented on 05.wc/wc.rb
> +  keys_to_keep << :name
keysにnameを含む前提の処理しか思いつかなかったので、こうなっていました。option_keysの変数名を考えても、nameを省くべきところだと思うので、省いて処理を変更しました。

了解です。そのように書き換えてみたらコードがスッキリして驚きました！

2024-08-01 17:12 UTC, u1tnk requested changes

2024-08-01 17:12 UTC, u1tnk commented on 05.wc/wc.rb
> +  [total]
ここ配列にして返してると思うのですが、出力処理の都合で配列にするなら出力処理でしましょう。

2024-08-01 17:12 UTC, u1tnk commented on 05.wc/wc.rb
> +    hash_for_totaling_values[:name] = 'total'
変数を分けているはずで、出力用の名前なら出力処理で補完すれば良いはずなので、ここでは入れる必要は無いです。

2024-08-01 17:12 UTC, u1tnk commented on 05.wc/wc.rb
> +def get_total(text_counts)
get_total という名前ですが プログラム(ruby以外も)慣習的に get_ はほぼそのまま変数を返すときに使います。
更にrubyだと get_は使わずに名前だけというのが慣習です。

なのでここではまあまあ複雑な計算もしているので totalを計算するとか作成するとかの意味があると良いですね。

2024-08-01 17:12 UTC, u1tnk commented on 05.wc/wc.rb
> +def get_text_counts(file_texts, file_names)
見逃してましたがここも get_はあまり良くないですね。

2024-08-01 17:12 UTC, u1tnk commented on 05.wc/wc.rb
> +  total = text_counts.each_with_object({}) do |text_count, hash_for_totaling_values|
hash_for_totaling_values  というブロック引数ですが、ブロック引数は数行のブロックであれば簡単なもので大丈夫です。
ここだと countsとかかなと。

ちなみにhashだけでもブロック変数なので良いですが、rubyだとできるだけ 型名は変数に付けない方が良いとされています。hashという型名より valueであれば keyでは無い事は明確だし、情報量が上がります。

2024-08-01 17:12 UTC, u1tnk commented on 05.wc/wc.rb
> +def render(text_counts, max_lengths, option_keys)
前回指摘したときに render/formatという関係は分かりづらいというところと renderとformatどちらかに合わせましょうという指摘もしたと思います。
なので render/render_text_counts もしくは format/format_text_counts にしましょう。

2024-08-02 02:08 UTC, u1tnk requested changes

2024-08-02 02:08 UTC, u1tnk commented on 05.wc/wc.rb
> +  [text_counts.each_with_object({}) do |text_count, counts|
ここで配列を返さないという指摘が対応できていません。
配列にするのは出力のためなので、計算するメソッドに混ざっている、すなわち出力処理に依存してしまっているからです。
そのメソッドの名前にふさわしい処理しかしないようにしましょう。

2024-08-02 02:08 UTC, u1tnk commented on 05.wc/wc.rb
> +    text_count.values.join(' ')
この join部分を format_text_counts側に移動すれば 一行分のformatとして独立できて、境界がはっきりしますね。format同士が依存しているのは仕方無いとこですが、役割の境界がよりスッキルするのと、totalの出力のときに format_text_countsの方を使えるのがメリットですね。

2024-08-03 15:52 UTC, u1tnk approved these changes

2024-08-18 02:30 UTC, merged